blog/urls.py
from blog.apps import BlogConfig
from django.urls import path
from .views import ( BlogPostListView,
    BlogPostDetailView,
    BlogPostCreateView,
    BlogPostUpdateView,
    BlogPostDeleteView,
    ContactView,
)

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogPostListView.as_view(), name='blog_list'),
    path('blog/create/', BlogPostCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogPostUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/', BlogPostDetailView.as_view(), name='blog_detail'),
    path('blog/<int:pk>/delete/', BlogPostDeleteView.as_view(), name='blog_delete'),
    path('contacts/', ContactView.as_view(), name='blog_contact'), ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalogs')),
    path('contacts/', include('catalog.urls', namespace='contacts')),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify



class BlogPost(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок блога')
    slug = slugify('Пример блога')
    description = models.TextField(null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='Изображение')
    created_at = models.DateField(auto_now_add=True)
    is_published = models.BooleanField(default=False, verbose_name='Уже тут')
    views_counter = models.PositiveIntegerField(verbose_name='Количество просмотров', default=0)

    def __str__(self):
        return f'{self.title} '

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/forms.py
from django import forms

from blog.models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ('views_count', )

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from blog.models import BlogPost
from django.urls import reverse_lazy, reverse

class BlogPostListView(ListView):
    model = BlogPost

    def get_queryset(self):
        return BlogPost.objects.filter(is_published=False)

class BlogPostCreateView(CreateView):
    model = BlogPost
    fields = ('title', 'description', 'slug')
    success_url = reverse_lazy('blog:blog_list')

    def get_object(self, queryset=None):
        slug = self.kwargs.get(self.slug_url_kwarg)
        queryset = queryset or self.get_queryset()
        return get_object_or_404(queryset, **{self.slug_field: slug})



class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):

        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object

class BlogPostUpdateView(UpdateView):
    model = BlogPost
    fields = ('title', 'description')
    success_url = reverse_lazy('blog:blog_list')

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])

class BlogPostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blog:blog_list')


class ContactView(TemplateView):
    template_name = 'blog/blog_contact.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

blog/templates/includes/inc_menu.html
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <h4>Заголовок</h4>
                <p class="text-body-secondary">Название блога</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                <h4>Навигация</h4>
                <ul class="list-unstyled">
                    <li><a href="{% url 'blog:blog_list' %}" class="text-white">Главная</a></li>
                    <li><a href="{% url 'blog:blog_contact' %}" class="text-white">Контакты</a></li>
                    <li><a href="#" class="text-white">Регистрация</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">

        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>